name: flutter_map_marker_cluster
description: A Dart implementation of Leaflet.makercluster for Flutter apps.
  Provides beautiful animated marker clustering functionality for flutter_map.
version: 1.3.4

homepage: https://github.com/youmtinet-flutter-packs/flutter_map_marker_cluster.git

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_map_marker_popup: ^6.1.2
  latlong2: ^0.9.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
